# railway.toml файл конфигурации для twitch-giveaway-bot

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
nodeEnv = "production"

[healthcheck]
path = "/health"
port = "$PORT"